//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsFava
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Input", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.Model")]
    public partial class Input : object
    {
        
        private wsFava.BankType BankTypeField;
        
        private string[] ParamsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsFava.BankType BankType
        {
            get
            {
                return this.BankTypeField;
            }
            set
            {
                this.BankTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Params
        {
            get
            {
                return this.ParamsField;
            }
            set
            {
                this.ParamsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankType", Namespace="http://schemas.datacontract.org/2004/07/Abc.Payment.Model")]
    public enum BankType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mellat = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pasargad = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Parsian = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FanapPos = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Saman = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sadad = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ikco = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IranKish = 8,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Output", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.Model")]
    public partial class Output : object
    {
        
        private string MessageField;
        
        private wsFava.Result ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsFava.Result Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.Model")]
    public enum Result : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResponseSuccess = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResponseFailure = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmtaDto", Namespace="http://schemas.datacontract.org/2004/07/Abc.Payment.Model")]
    public partial class EmtaDto : object
    {
        
        private wsFava.EmtaOutput emtaOutputField;
        
        private wsFava.Identity identityField;
        
        private wsFava.PrimaryBankCard primaryBankCardField;
        
        private wsFava.PrimaryMobileNumber primaryMobileNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsFava.EmtaOutput emtaOutput
        {
            get
            {
                return this.emtaOutputField;
            }
            set
            {
                this.emtaOutputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsFava.Identity identity
        {
            get
            {
                return this.identityField;
            }
            set
            {
                this.identityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsFava.PrimaryBankCard primaryBankCard
        {
            get
            {
                return this.primaryBankCardField;
            }
            set
            {
                this.primaryBankCardField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsFava.PrimaryMobileNumber primaryMobileNumber
        {
            get
            {
                return this.primaryMobileNumberField;
            }
            set
            {
                this.primaryMobileNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmtaOutput", Namespace="http://schemas.datacontract.org/2004/07/Abc.Payment.Model")]
    public partial class EmtaOutput : object
    {
        
        private string access_tokenField;
        
        private string errorField;
        
        private int expires_inField;
        
        private string scopeField;
        
        private string token_typeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string access_token
        {
            get
            {
                return this.access_tokenField;
            }
            set
            {
                this.access_tokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int expires_in
        {
            get
            {
                return this.expires_inField;
            }
            set
            {
                this.expires_inField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string scope
        {
            get
            {
                return this.scopeField;
            }
            set
            {
                this.scopeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token_type
        {
            get
            {
                return this.token_typeField;
            }
            set
            {
                this.token_typeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Identity", Namespace="http://schemas.datacontract.org/2004/07/Abc.Payment.Model")]
    public partial class Identity : object
    {
        
        private int birthDateField;
        
        private string familyField;
        
        private string fatherNameField;
        
        private string genderField;
        
        private string nameField;
        
        private string nationalIdField;
        
        private string officeNameField;
        
        private string shenasnameNoField;
        
        private string shenasnameSeriField;
        
        private string shenasnameSerialField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int birthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string family
        {
            get
            {
                return this.familyField;
            }
            set
            {
                this.familyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fatherName
        {
            get
            {
                return this.fatherNameField;
            }
            set
            {
                this.fatherNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nationalId
        {
            get
            {
                return this.nationalIdField;
            }
            set
            {
                this.nationalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string officeName
        {
            get
            {
                return this.officeNameField;
            }
            set
            {
                this.officeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shenasnameNo
        {
            get
            {
                return this.shenasnameNoField;
            }
            set
            {
                this.shenasnameNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shenasnameSeri
        {
            get
            {
                return this.shenasnameSeriField;
            }
            set
            {
                this.shenasnameSeriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shenasnameSerial
        {
            get
            {
                return this.shenasnameSerialField;
            }
            set
            {
                this.shenasnameSerialField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrimaryBankCard", Namespace="http://schemas.datacontract.org/2004/07/Abc.Payment.Model")]
    public partial class PrimaryBankCard : object
    {
        
        private string cardNumberField;
        
        private bool primaryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cardNumber
        {
            get
            {
                return this.cardNumberField;
            }
            set
            {
                this.cardNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool primary
        {
            get
            {
                return this.primaryField;
            }
            set
            {
                this.primaryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrimaryMobileNumber", Namespace="http://schemas.datacontract.org/2004/07/Abc.Payment.Model")]
    public partial class PrimaryMobileNumber : object
    {
        
        private string mobileNumberField;
        
        private bool primaryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mobileNumber
        {
            get
            {
                return this.mobileNumberField;
            }
            set
            {
                this.mobileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool primary
        {
            get
            {
                return this.primaryField;
            }
            set
            {
                this.primaryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShebaDto", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.Model")]
    public partial class ShebaDto : object
    {
        
        private string BankCodeField;
        
        private string BankNameField;
        
        private string DepositNumberField;
        
        private string IbanTypeField;
        
        private wsFava.OwnersInfo[] OwnersInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankCode
        {
            get
            {
                return this.BankCodeField;
            }
            set
            {
                this.BankCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankName
        {
            get
            {
                return this.BankNameField;
            }
            set
            {
                this.BankNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepositNumber
        {
            get
            {
                return this.DepositNumberField;
            }
            set
            {
                this.DepositNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IbanType
        {
            get
            {
                return this.IbanTypeField;
            }
            set
            {
                this.IbanTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsFava.OwnersInfo[] OwnersInfo
        {
            get
            {
                return this.OwnersInfoField;
            }
            set
            {
                this.OwnersInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OwnersInfo", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.Model")]
    public partial class OwnersInfo : object
    {
        
        private string FirstNameField;
        
        private string LastNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReverseResultData", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.PasargadBank.Model")]
    public partial class ReverseResultData : object
    {
        
        private string AmountField;
        
        private string DescriptionField;
        
        private string OrderIdField;
        
        private int ResCodeField;
        
        private string RetrivalRefNoField;
        
        private string SystemTraceNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResCode
        {
            get
            {
                return this.ResCodeField;
            }
            set
            {
                this.ResCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RetrivalRefNo
        {
            get
            {
                return this.RetrivalRefNoField;
            }
            set
            {
                this.RetrivalRefNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemTraceNo
        {
            get
            {
                return this.SystemTraceNoField;
            }
            set
            {
                this.SystemTraceNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="transactionModel", Namespace="http://schemas.datacontract.org/2004/07/VerifyPayment")]
    public partial class transactionModel : object
    {
        
        private string AMOUNTField;
        
        private string CARDNOField;
        
        private string EXTRAPARAM1Field;
        
        private string EXTRAPARAM2Field;
        
        private string EXTRAPARAM3Field;
        
        private string EXTRAPARAM4Field;
        
        private string MERCHANTIDField;
        
        private string PAYMENTIDField;
        
        private string REFERENCENUMBERField;
        
        private string RESULTCODEField;
        
        private string ROWNUMBERField;
        
        private string SETTLEMENTDATEField;
        
        private string SPECIALPAYMENTIDField;
        
        private string TRANSDATEField;
        
        private string VERIFYDATEField;
        
        private string VERIFYRESPONSEField;
        
        private string invoceNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AMOUNT
        {
            get
            {
                return this.AMOUNTField;
            }
            set
            {
                this.AMOUNTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CARDNO
        {
            get
            {
                return this.CARDNOField;
            }
            set
            {
                this.CARDNOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXTRAPARAM1
        {
            get
            {
                return this.EXTRAPARAM1Field;
            }
            set
            {
                this.EXTRAPARAM1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXTRAPARAM2
        {
            get
            {
                return this.EXTRAPARAM2Field;
            }
            set
            {
                this.EXTRAPARAM2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXTRAPARAM3
        {
            get
            {
                return this.EXTRAPARAM3Field;
            }
            set
            {
                this.EXTRAPARAM3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXTRAPARAM4
        {
            get
            {
                return this.EXTRAPARAM4Field;
            }
            set
            {
                this.EXTRAPARAM4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MERCHANTID
        {
            get
            {
                return this.MERCHANTIDField;
            }
            set
            {
                this.MERCHANTIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PAYMENTID
        {
            get
            {
                return this.PAYMENTIDField;
            }
            set
            {
                this.PAYMENTIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REFERENCENUMBER
        {
            get
            {
                return this.REFERENCENUMBERField;
            }
            set
            {
                this.REFERENCENUMBERField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RESULTCODE
        {
            get
            {
                return this.RESULTCODEField;
            }
            set
            {
                this.RESULTCODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ROWNUMBER
        {
            get
            {
                return this.ROWNUMBERField;
            }
            set
            {
                this.ROWNUMBERField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SETTLEMENTDATE
        {
            get
            {
                return this.SETTLEMENTDATEField;
            }
            set
            {
                this.SETTLEMENTDATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SPECIALPAYMENTID
        {
            get
            {
                return this.SPECIALPAYMENTIDField;
            }
            set
            {
                this.SPECIALPAYMENTIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TRANSDATE
        {
            get
            {
                return this.TRANSDATEField;
            }
            set
            {
                this.TRANSDATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VERIFYDATE
        {
            get
            {
                return this.VERIFYDATEField;
            }
            set
            {
                this.VERIFYDATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VERIFYRESPONSE
        {
            get
            {
                return this.VERIFYRESPONSEField;
            }
            set
            {
                this.VERIFYRESPONSEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string invoceNo
        {
            get
            {
                return this.invoceNoField;
            }
            set
            {
                this.invoceNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="responseModel", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.ir.moi.naji")]
    public partial class responseModel : object
    {
        
        private string codeFieldField;
        
        private string descFieldField;
        
        private string resultFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codeField
        {
            get
            {
                return this.codeFieldField;
            }
            set
            {
                this.codeFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string descField
        {
            get
            {
                return this.descFieldField;
            }
            set
            {
                this.descFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string resultField
        {
            get
            {
                return this.resultFieldField;
            }
            set
            {
                this.resultFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseOutput", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.Model.ViewModel.Base")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsFava.GetSaipaCustomersViewModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsFava.GetSaipaCustomersBlackListViewModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsFava.GetSaipaLotteryWinnersViewModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsFava.SaipaResponsePostMethodViewModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsFava.SipaAuthorizationViewModel))]
    public partial class BaseOutput : object
    {
        
        private string errorField;
        
        private string messageField;
        
        private bool successField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSaipaCustomersViewModel", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.Model.ViewModel.Saipa")]
    public partial class GetSaipaCustomersViewModel : wsFava.BaseOutput
    {
        
        private wsFava.GetSaipaCustomersData dataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsFava.GetSaipaCustomersData data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSaipaCustomersBlackListViewModel", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.Model.ViewModel.Saipa")]
    public partial class GetSaipaCustomersBlackListViewModel : wsFava.BaseOutput
    {
        
        private wsFava.SaipaCustomersBlackListData[] dataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsFava.SaipaCustomersBlackListData[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSaipaLotteryWinnersViewModel", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.Model.ViewModel.Saipa")]
    public partial class GetSaipaLotteryWinnersViewModel : wsFava.BaseOutput
    {
        
        private wsFava.GetSaipaLotteryWinnersData dataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsFava.GetSaipaLotteryWinnersData data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaipaResponsePostMethodViewModel", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.Model.ViewModel.Saipa")]
    public partial class SaipaResponsePostMethodViewModel : wsFava.BaseOutput
    {
        
        private wsFava.ResponseData dataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsFava.ResponseData data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SipaAuthorizationViewModel", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.Model.ViewModel.Saipa")]
    public partial class SipaAuthorizationViewModel : wsFava.BaseOutput
    {
        
        private wsFava.SipaAuthorizationData dataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsFava.SipaAuthorizationData data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SipaAuthorizationData", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.Model.ViewModel.Saipa")]
    public partial class SipaAuthorizationData : object
    {
        
        private string access_tokenField;
        
        private string token_typeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string access_token
        {
            get
            {
                return this.access_tokenField;
            }
            set
            {
                this.access_tokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token_type
        {
            get
            {
                return this.token_typeField;
            }
            set
            {
                this.token_typeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSaipaCustomersData", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.Model.ViewModel.Saipa")]
    public partial class GetSaipaCustomersData : object
    {
        
        private wsFava.CustomersData[] CustomersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsFava.CustomersData[] Customers
        {
            get
            {
                return this.CustomersField;
            }
            set
            {
                this.CustomersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomersData", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.Model.ViewModel.Saipa")]
    public partial class CustomersData : object
    {
        
        private string NATIONAL_IDField;
        
        private long RQST_DATEField;
        
        private long RQST_NOField;
        
        private decimal STATUSField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NATIONAL_ID
        {
            get
            {
                return this.NATIONAL_IDField;
            }
            set
            {
                this.NATIONAL_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RQST_DATE
        {
            get
            {
                return this.RQST_DATEField;
            }
            set
            {
                this.RQST_DATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RQST_NO
        {
            get
            {
                return this.RQST_NOField;
            }
            set
            {
                this.RQST_NOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal STATUS
        {
            get
            {
                return this.STATUSField;
            }
            set
            {
                this.STATUSField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaipaCustomersBlackListData", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.Model.ViewModel.Saipa")]
    public partial class SaipaCustomersBlackListData : object
    {
        
        private string last_buy_dateField;
        
        private string national_idField;
        
        private int rec_typeField;
        
        private int statusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string last_buy_date
        {
            get
            {
                return this.last_buy_dateField;
            }
            set
            {
                this.last_buy_dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string national_id
        {
            get
            {
                return this.national_idField;
            }
            set
            {
                this.national_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rec_type
        {
            get
            {
                return this.rec_typeField;
            }
            set
            {
                this.rec_typeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSaipaLotteryWinnersData", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.Model.ViewModel.Saipa")]
    public partial class GetSaipaLotteryWinnersData : object
    {
        
        private wsFava.LotteryWinnersData[] TableField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsFava.LotteryWinnersData[] Table
        {
            get
            {
                return this.TableField;
            }
            set
            {
                this.TableField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LotteryWinnersData", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.Model.ViewModel.Saipa")]
    public partial class LotteryWinnersData : object
    {
        
        private string NATIONAL_IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NATIONAL_ID
        {
            get
            {
                return this.NATIONAL_IDField;
            }
            set
            {
                this.NATIONAL_IDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseData", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.Model.ViewModel.Saipa")]
    public partial class ResponseData : object
    {
        
        private string MessageField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSaipaCustomersDTO", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.Model.DTOs.Saipa")]
    public partial class GetSaipaCustomersDTO : object
    {
        
        private int flagField;
        
        private string fromDateField;
        
        private string toDateField;
        
        private string tokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int flag
        {
            get
            {
                return this.flagField;
            }
            set
            {
                this.flagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fromDate
        {
            get
            {
                return this.fromDateField;
            }
            set
            {
                this.fromDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string toDate
        {
            get
            {
                return this.toDateField;
            }
            set
            {
                this.toDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSaipaLotteryWinnersDTO", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.Model.DTOs.Saipa")]
    public partial class GetSaipaLotteryWinnersDTO : object
    {
        
        private string tokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaipaRegisterRecivedCustomersDTO", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.Model.DTOs.Saipa")]
    public partial class SaipaRegisterRecivedCustomersDTO : object
    {
        
        private wsFava.RegisterRecivedCustomerData[] dataField;
        
        private string tokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsFava.RegisterRecivedCustomerData[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterRecivedCustomerData", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.Model.DTOs.Saipa")]
    public partial class RegisterRecivedCustomerData : object
    {
        
        private string Ikco_traceField;
        
        private long rqst_noField;
        
        private int statusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ikco_trace
        {
            get
            {
                return this.Ikco_traceField;
            }
            set
            {
                this.Ikco_traceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long rqst_no
        {
            get
            {
                return this.rqst_noField;
            }
            set
            {
                this.rqst_noField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaipaRegisterReceivedWinnersDTO", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.Model.DTOs.Saipa")]
    public partial class SaipaRegisterReceivedWinnersDTO : object
    {
        
        private wsFava.RegisterReceivedWinnerData[] dataField;
        
        private string tokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsFava.RegisterReceivedWinnerData[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterReceivedWinnerData", Namespace="http://schemas.datacontract.org/2004/07/Abc.Gateway.Model.DTOs.Saipa")]
    public partial class RegisterReceivedWinnerData : object
    {
        
        private string ikco_tracking_codeField;
        
        private string national_idField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ikco_tracking_code
        {
            get
            {
                return this.ikco_tracking_codeField;
            }
            set
            {
                this.ikco_tracking_codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string national_id
        {
            get
            {
                return this.national_idField;
            }
            set
            {
                this.national_idField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsFava.IGatewayService")]
    public interface IGatewayService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/GetTimeSpam", ReplyAction="http://tempuri.org/IGatewayService/GetTimeSpamResponse")]
        System.Threading.Tasks.Task<int> GetTimeSpamAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/Pay", ReplyAction="http://tempuri.org/IGatewayService/PayResponse")]
        System.Threading.Tasks.Task<wsFava.Output> PayAsync(wsFava.Input input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/Verify", ReplyAction="http://tempuri.org/IGatewayService/VerifyResponse")]
        System.Threading.Tasks.Task<wsFava.Output> VerifyAsync(wsFava.Input input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/Inquiry", ReplyAction="http://tempuri.org/IGatewayService/InquiryResponse")]
        System.Threading.Tasks.Task<wsFava.Output> InquiryAsync(wsFava.Input input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/Settle", ReplyAction="http://tempuri.org/IGatewayService/SettleResponse")]
        System.Threading.Tasks.Task<wsFava.Output> SettleAsync(wsFava.Input input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/SettleForSSIS", ReplyAction="http://tempuri.org/IGatewayService/SettleForSSISResponse")]
        System.Threading.Tasks.Task<wsFava.Output> SettleForSSISAsync(string[] Params);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/InquiryForSSIS", ReplyAction="http://tempuri.org/IGatewayService/InquiryForSSISResponse")]
        System.Threading.Tasks.Task<wsFava.Output> InquiryForSSISAsync(string[] Params);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/VerifyForSSIS", ReplyAction="http://tempuri.org/IGatewayService/VerifyForSSISResponse")]
        System.Threading.Tasks.Task<wsFava.Output> VerifyForSSISAsync(string[] Params);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/ValidateCaptcha", ReplyAction="http://tempuri.org/IGatewayService/ValidateCaptchaResponse")]
        System.Threading.Tasks.Task<string> ValidateCaptchaAsync(string recaptchaResponse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/GeneralValidateCaptcha", ReplyAction="http://tempuri.org/IGatewayService/GeneralValidateCaptchaResponse")]
        System.Threading.Tasks.Task<string> GeneralValidateCaptchaAsync(string recaptchaResponse, string iSsuance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/CheckConnectionToGateWay", ReplyAction="http://tempuri.org/IGatewayService/CheckConnectionToGateWayResponse")]
        System.Threading.Tasks.Task<int> CheckConnectionToGateWayAsync(int input1, int input2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/GetDataFromEmta", ReplyAction="http://tempuri.org/IGatewayService/GetDataFromEmtaResponse")]
        System.Threading.Tasks.Task<wsFava.EmtaDto> GetDataFromEmtaAsync(string[] Params);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/GetShebas", ReplyAction="http://tempuri.org/IGatewayService/GetShebasResponse")]
        System.Threading.Tasks.Task<wsFava.ShebaDto> GetShebasAsync(string sheba, string ip, string mobile, string clienthttp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/CheckConnectionToMellat", ReplyAction="http://tempuri.org/IGatewayService/CheckConnectionToMellatResponse")]
        System.Threading.Tasks.Task<bool> CheckConnectionToMellatAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/CheckConnectionToParsian", ReplyAction="http://tempuri.org/IGatewayService/CheckConnectionToParsianResponse")]
        System.Threading.Tasks.Task<bool> CheckConnectionToParsianAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/CheckConnectionToSaman", ReplyAction="http://tempuri.org/IGatewayService/CheckConnectionToSamanResponse")]
        System.Threading.Tasks.Task<bool> CheckConnectionToSamanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/CheckConnectionToSadad", ReplyAction="http://tempuri.org/IGatewayService/CheckConnectionToSadadResponse")]
        System.Threading.Tasks.Task<bool> CheckConnectionToSadadAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/CheckConnectionToIranKish", ReplyAction="http://tempuri.org/IGatewayService/CheckConnectionToIranKishResponse")]
        System.Threading.Tasks.Task<bool> CheckConnectionToIranKishAsync();
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/ReverseSaman", ReplyAction="http://tempuri.org/IGatewayService/ReverseSamanResponse")]
        System.Threading.Tasks.Task<wsFava.ReverseSamanResponse> ReverseSamanAsync(wsFava.ReverseSamanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/ReverseMellat", ReplyAction="http://tempuri.org/IGatewayService/ReverseMellatResponse")]
        System.Threading.Tasks.Task<string> ReverseMellatAsync(string terminal, string userName, string password, int payResId, string transactionCode, bool exceptionerror);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/ReverseParsian", ReplyAction="http://tempuri.org/IGatewayService/ReverseParsianResponse")]
        System.Threading.Tasks.Task<wsFava.ReverseParsianResponse> ReverseParsianAsync(wsFava.ReverseParsianRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/ReverseSadad", ReplyAction="http://tempuri.org/IGatewayService/ReverseSadadResponse")]
        System.Threading.Tasks.Task<wsFava.ReverseSadadResponse> ReverseSadadAsync(wsFava.ReverseSadadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/ReverseIranKish", ReplyAction="http://tempuri.org/IGatewayService/ReverseIranKishResponse")]
        System.Threading.Tasks.Task<string> ReverseIranKishAsync(string token, string terminalid, string systemTraceAuditNumber, string TransactionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/ReverseIkco", ReplyAction="http://tempuri.org/IGatewayService/ReverseIkcoResponse")]
        System.Threading.Tasks.Task<string> ReverseIkcoAsync(string userName, string password, string token, string additionalData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/ConflictParsian", ReplyAction="http://tempuri.org/IGatewayService/ConflictParsianResponse")]
        System.Threading.Tasks.Task<string> ConflictParsianAsync(System.DateTime FromDate, System.DateTime ToDate, System.Nullable<long> RRN, System.Nullable<long> OrderId, System.Nullable<long> Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/ConflictSadad", ReplyAction="http://tempuri.org/IGatewayService/ConflictSadadResponse")]
        System.Threading.Tasks.Task<string> ConflictSadadAsync(string[] Terminals, int TransactionStatus, int PageSize, int PageNumber, string FromDate, string ToDate, string ReferenceNumber, string CardNumber, string DateTimeCultureType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/ConflictSaman", ReplyAction="http://tempuri.org/IGatewayService/ConflictSamanResponse")]
        System.Threading.Tasks.Task<string> ConflictSamanAsync(string ResNum, System.DateTime fromDate, System.DateTime toDate, string Terminal, string RefNum, string Pan, int Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/ConflictIranKish", ReplyAction="http://tempuri.org/IGatewayService/ConflictIranKishResponse")]
        System.Threading.Tasks.Task<wsFava.transactionModel[]> ConflictIranKishAsync(string Terminal, string fromDate, string toDate, string offset, string limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/ConflictMellatNew", ReplyAction="http://tempuri.org/IGatewayService/ConflictMellatNewResponse")]
        System.Threading.Tasks.Task<wsFava.Output> ConflictMellatNewAsync(wsFava.Input input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/ConflictParsianNew", ReplyAction="http://tempuri.org/IGatewayService/ConflictParsianNewResponse")]
        System.Threading.Tasks.Task<wsFava.Output> ConflictParsianNewAsync(wsFava.Input input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/ConflictSamanNew", ReplyAction="http://tempuri.org/IGatewayService/ConflictSamanNewResponse")]
        System.Threading.Tasks.Task<wsFava.Output> ConflictSamanNewAsync(wsFava.Input input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/ConflictSadadNew", ReplyAction="http://tempuri.org/IGatewayService/ConflictSadadNewResponse")]
        System.Threading.Tasks.Task<wsFava.Output> ConflictSadadNewAsync(wsFava.Input input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/ConflictIranKishNew", ReplyAction="http://tempuri.org/IGatewayService/ConflictIranKishNewResponse")]
        System.Threading.Tasks.Task<wsFava.Output> ConflictIranKishNewAsync(wsFava.Input input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/NajaCheckNUM", ReplyAction="http://tempuri.org/IGatewayService/NajaCheckNUMResponse")]
        System.Threading.Tasks.Task<wsFava.responseModel> NajaCheckNUMAsync(string Nationalcode, string a, string b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/NajaCheckLic", ReplyAction="http://tempuri.org/IGatewayService/NajaCheckLicResponse")]
        System.Threading.Tasks.Task<wsFava.responseModel> NajaCheckLicAsync(string Nationalcode, string a, string b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/NajaCheckNUMTest", ReplyAction="http://tempuri.org/IGatewayService/NajaCheckNUMTestResponse")]
        System.Threading.Tasks.Task<wsFava.responseModel> NajaCheckNUMTestAsync(string Nationalcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/NajaCheckLicTest", ReplyAction="http://tempuri.org/IGatewayService/NajaCheckLicTestResponse")]
        System.Threading.Tasks.Task<wsFava.responseModel> NajaCheckLicTestAsync(string Nationalcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/SaipaLogin", ReplyAction="http://tempuri.org/IGatewayService/SaipaLoginResponse")]
        System.Threading.Tasks.Task<wsFava.SipaAuthorizationViewModel> SaipaLoginAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/Test", ReplyAction="http://tempuri.org/IGatewayService/TestResponse")]
        System.Threading.Tasks.Task<wsFava.SipaAuthorizationViewModel> TestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/GetSaipaCustomers", ReplyAction="http://tempuri.org/IGatewayService/GetSaipaCustomersResponse")]
        System.Threading.Tasks.Task<wsFava.GetSaipaCustomersViewModel> GetSaipaCustomersAsync(wsFava.GetSaipaCustomersDTO param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/GetLastBuyByDate", ReplyAction="http://tempuri.org/IGatewayService/GetLastBuyByDateResponse")]
        System.Threading.Tasks.Task<wsFava.GetSaipaCustomersBlackListViewModel> GetLastBuyByDateAsync(wsFava.GetSaipaCustomersDTO param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/GetSaipaLotteryWinners", ReplyAction="http://tempuri.org/IGatewayService/GetSaipaLotteryWinnersResponse")]
        System.Threading.Tasks.Task<wsFava.GetSaipaLotteryWinnersViewModel> GetSaipaLotteryWinnersAsync(wsFava.GetSaipaLotteryWinnersDTO param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/SaipaRegisterRecivedCustomers", ReplyAction="http://tempuri.org/IGatewayService/SaipaRegisterRecivedCustomersResponse")]
        System.Threading.Tasks.Task<wsFava.SaipaResponsePostMethodViewModel> SaipaRegisterRecivedCustomersAsync(wsFava.SaipaRegisterRecivedCustomersDTO param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/SaipaRegisterReceivedWinners", ReplyAction="http://tempuri.org/IGatewayService/SaipaRegisterReceivedWinnersResponse")]
        System.Threading.Tasks.Task<wsFava.SaipaResponsePostMethodViewModel> SaipaRegisterReceivedWinnersAsync(wsFava.SaipaRegisterReceivedWinnersDTO param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/sha3_512_hasher", ReplyAction="http://tempuri.org/IGatewayService/sha3_512_hasherResponse")]
        System.Threading.Tasks.Task<string> sha3_512_hasherAsync(string input, System.Nullable<bool> useHodaPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/HodaAuth", ReplyAction="http://tempuri.org/IGatewayService/HodaAuthResponse")]
        System.Threading.Tasks.Task<string> HodaAuthAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/GetDataFromHoda", ReplyAction="http://tempuri.org/IGatewayService/GetDataFromHodaResponse")]
        System.Threading.Tasks.Task<string> GetDataFromHodaAsync(string AuthAssertion, string RefId, string SpReqId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGatewayService/Version", ReplyAction="http://tempuri.org/IGatewayService/VersionResponse")]
        System.Threading.Tasks.Task<string> VersionAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReverseSaman", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReverseSamanRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string RefNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int TerminalNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool exceptionerror;
        
        public ReverseSamanRequest()
        {
        }
        
        public ReverseSamanRequest(string RefNum, int TerminalNumber, bool exceptionerror)
        {
            this.RefNum = RefNum;
            this.TerminalNumber = TerminalNumber;
            this.exceptionerror = exceptionerror;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReverseSamanResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReverseSamanResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public double ReverseSamanResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errordesc;
        
        public ReverseSamanResponse()
        {
        }
        
        public ReverseSamanResponse(double ReverseSamanResult, string errordesc)
        {
            this.ReverseSamanResult = ReverseSamanResult;
            this.errordesc = errordesc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReverseParsian", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReverseParsianRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool exceptionerror;
        
        public ReverseParsianRequest()
        {
        }
        
        public ReverseParsianRequest(string pin, string token, bool exceptionerror)
        {
            this.pin = pin;
            this.token = token;
            this.exceptionerror = exceptionerror;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReverseParsianResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReverseParsianResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public short ReverseParsianResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errordesc;
        
        public ReverseParsianResponse()
        {
        }
        
        public ReverseParsianResponse(short ReverseParsianResult, string errordesc)
        {
            this.ReverseParsianResult = ReverseParsianResult;
            this.errordesc = errordesc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReverseSadad", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReverseSadadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string terminalId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string merchantId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public decimal amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public bool exceptionerror;
        
        public ReverseSadadRequest()
        {
        }
        
        public ReverseSadadRequest(string pin, string token, string terminalId, string merchantId, decimal amount, bool exceptionerror)
        {
            this.pin = pin;
            this.token = token;
            this.terminalId = terminalId;
            this.merchantId = merchantId;
            this.amount = amount;
            this.exceptionerror = exceptionerror;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReverseSadadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReverseSadadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public wsFava.ReverseResultData ReverseSadadResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errordesc;
        
        public ReverseSadadResponse()
        {
        }
        
        public ReverseSadadResponse(wsFava.ReverseResultData ReverseSadadResult, string errordesc)
        {
            this.ReverseSadadResult = ReverseSadadResult;
            this.errordesc = errordesc;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IGatewayServiceChannel : wsFava.IGatewayService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class GatewayServiceClient : System.ServiceModel.ClientBase<wsFava.IGatewayService>, wsFava.IGatewayService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GatewayServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(GatewayServiceClient.GetBindingForEndpoint(endpointConfiguration), GatewayServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GatewayServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GatewayServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GatewayServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GatewayServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GatewayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> GetTimeSpamAsync()
        {
            return base.Channel.GetTimeSpamAsync();
        }
        
        public System.Threading.Tasks.Task<wsFava.Output> PayAsync(wsFava.Input input)
        {
            return base.Channel.PayAsync(input);
        }
        
        public System.Threading.Tasks.Task<wsFava.Output> VerifyAsync(wsFava.Input input)
        {
            return base.Channel.VerifyAsync(input);
        }
        
        public System.Threading.Tasks.Task<wsFava.Output> InquiryAsync(wsFava.Input input)
        {
            return base.Channel.InquiryAsync(input);
        }
        
        public System.Threading.Tasks.Task<wsFava.Output> SettleAsync(wsFava.Input input)
        {
            return base.Channel.SettleAsync(input);
        }
        
        public System.Threading.Tasks.Task<wsFava.Output> SettleForSSISAsync(string[] Params)
        {
            return base.Channel.SettleForSSISAsync(Params);
        }
        
        public System.Threading.Tasks.Task<wsFava.Output> InquiryForSSISAsync(string[] Params)
        {
            return base.Channel.InquiryForSSISAsync(Params);
        }
        
        public System.Threading.Tasks.Task<wsFava.Output> VerifyForSSISAsync(string[] Params)
        {
            return base.Channel.VerifyForSSISAsync(Params);
        }
        
        public System.Threading.Tasks.Task<string> ValidateCaptchaAsync(string recaptchaResponse)
        {
            return base.Channel.ValidateCaptchaAsync(recaptchaResponse);
        }
        
        public System.Threading.Tasks.Task<string> GeneralValidateCaptchaAsync(string recaptchaResponse, string iSsuance)
        {
            return base.Channel.GeneralValidateCaptchaAsync(recaptchaResponse, iSsuance);
        }
        
        public System.Threading.Tasks.Task<int> CheckConnectionToGateWayAsync(int input1, int input2)
        {
            return base.Channel.CheckConnectionToGateWayAsync(input1, input2);
        }
        
        public System.Threading.Tasks.Task<wsFava.EmtaDto> GetDataFromEmtaAsync(string[] Params)
        {
            return base.Channel.GetDataFromEmtaAsync(Params);
        }
        
        public System.Threading.Tasks.Task<wsFava.ShebaDto> GetShebasAsync(string sheba, string ip, string mobile, string clienthttp)
        {
            return base.Channel.GetShebasAsync(sheba, ip, mobile, clienthttp);
        }
        
        public System.Threading.Tasks.Task<bool> CheckConnectionToMellatAsync()
        {
            return base.Channel.CheckConnectionToMellatAsync();
        }
        
        public System.Threading.Tasks.Task<bool> CheckConnectionToParsianAsync()
        {
            return base.Channel.CheckConnectionToParsianAsync();
        }
        
        public System.Threading.Tasks.Task<bool> CheckConnectionToSamanAsync()
        {
            return base.Channel.CheckConnectionToSamanAsync();
        }
        
        public System.Threading.Tasks.Task<bool> CheckConnectionToSadadAsync()
        {
            return base.Channel.CheckConnectionToSadadAsync();
        }
        
        public System.Threading.Tasks.Task<bool> CheckConnectionToIranKishAsync()
        {
            return base.Channel.CheckConnectionToIranKishAsync();
        }
        
        public System.Threading.Tasks.Task<wsFava.ReverseSamanResponse> ReverseSamanAsync(wsFava.ReverseSamanRequest request)
        {
            return base.Channel.ReverseSamanAsync(request);
        }
        
        public System.Threading.Tasks.Task<string> ReverseMellatAsync(string terminal, string userName, string password, int payResId, string transactionCode, bool exceptionerror)
        {
            return base.Channel.ReverseMellatAsync(terminal, userName, password, payResId, transactionCode, exceptionerror);
        }
        
        public System.Threading.Tasks.Task<wsFava.ReverseParsianResponse> ReverseParsianAsync(wsFava.ReverseParsianRequest request)
        {
            return base.Channel.ReverseParsianAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsFava.ReverseSadadResponse> ReverseSadadAsync(wsFava.ReverseSadadRequest request)
        {
            return base.Channel.ReverseSadadAsync(request);
        }
        
        public System.Threading.Tasks.Task<string> ReverseIranKishAsync(string token, string terminalid, string systemTraceAuditNumber, string TransactionCode)
        {
            return base.Channel.ReverseIranKishAsync(token, terminalid, systemTraceAuditNumber, TransactionCode);
        }
        
        public System.Threading.Tasks.Task<string> ReverseIkcoAsync(string userName, string password, string token, string additionalData)
        {
            return base.Channel.ReverseIkcoAsync(userName, password, token, additionalData);
        }
        
        public System.Threading.Tasks.Task<string> ConflictParsianAsync(System.DateTime FromDate, System.DateTime ToDate, System.Nullable<long> RRN, System.Nullable<long> OrderId, System.Nullable<long> Token)
        {
            return base.Channel.ConflictParsianAsync(FromDate, ToDate, RRN, OrderId, Token);
        }
        
        public System.Threading.Tasks.Task<string> ConflictSadadAsync(string[] Terminals, int TransactionStatus, int PageSize, int PageNumber, string FromDate, string ToDate, string ReferenceNumber, string CardNumber, string DateTimeCultureType)
        {
            return base.Channel.ConflictSadadAsync(Terminals, TransactionStatus, PageSize, PageNumber, FromDate, ToDate, ReferenceNumber, CardNumber, DateTimeCultureType);
        }
        
        public System.Threading.Tasks.Task<string> ConflictSamanAsync(string ResNum, System.DateTime fromDate, System.DateTime toDate, string Terminal, string RefNum, string Pan, int Status)
        {
            return base.Channel.ConflictSamanAsync(ResNum, fromDate, toDate, Terminal, RefNum, Pan, Status);
        }
        
        public System.Threading.Tasks.Task<wsFava.transactionModel[]> ConflictIranKishAsync(string Terminal, string fromDate, string toDate, string offset, string limit)
        {
            return base.Channel.ConflictIranKishAsync(Terminal, fromDate, toDate, offset, limit);
        }
        
        public System.Threading.Tasks.Task<wsFava.Output> ConflictMellatNewAsync(wsFava.Input input)
        {
            return base.Channel.ConflictMellatNewAsync(input);
        }
        
        public System.Threading.Tasks.Task<wsFava.Output> ConflictParsianNewAsync(wsFava.Input input)
        {
            return base.Channel.ConflictParsianNewAsync(input);
        }
        
        public System.Threading.Tasks.Task<wsFava.Output> ConflictSamanNewAsync(wsFava.Input input)
        {
            return base.Channel.ConflictSamanNewAsync(input);
        }
        
        public System.Threading.Tasks.Task<wsFava.Output> ConflictSadadNewAsync(wsFava.Input input)
        {
            return base.Channel.ConflictSadadNewAsync(input);
        }
        
        public System.Threading.Tasks.Task<wsFava.Output> ConflictIranKishNewAsync(wsFava.Input input)
        {
            return base.Channel.ConflictIranKishNewAsync(input);
        }
        
        public System.Threading.Tasks.Task<wsFava.responseModel> NajaCheckNUMAsync(string Nationalcode, string a, string b)
        {
            return base.Channel.NajaCheckNUMAsync(Nationalcode, a, b);
        }
        
        public System.Threading.Tasks.Task<wsFava.responseModel> NajaCheckLicAsync(string Nationalcode, string a, string b)
        {
            return base.Channel.NajaCheckLicAsync(Nationalcode, a, b);
        }
        
        public System.Threading.Tasks.Task<wsFava.responseModel> NajaCheckNUMTestAsync(string Nationalcode)
        {
            return base.Channel.NajaCheckNUMTestAsync(Nationalcode);
        }
        
        public System.Threading.Tasks.Task<wsFava.responseModel> NajaCheckLicTestAsync(string Nationalcode)
        {
            return base.Channel.NajaCheckLicTestAsync(Nationalcode);
        }
        
        public System.Threading.Tasks.Task<wsFava.SipaAuthorizationViewModel> SaipaLoginAsync()
        {
            return base.Channel.SaipaLoginAsync();
        }
        
        public System.Threading.Tasks.Task<wsFava.SipaAuthorizationViewModel> TestAsync()
        {
            return base.Channel.TestAsync();
        }
        
        public System.Threading.Tasks.Task<wsFava.GetSaipaCustomersViewModel> GetSaipaCustomersAsync(wsFava.GetSaipaCustomersDTO param)
        {
            return base.Channel.GetSaipaCustomersAsync(param);
        }
        
        public System.Threading.Tasks.Task<wsFava.GetSaipaCustomersBlackListViewModel> GetLastBuyByDateAsync(wsFava.GetSaipaCustomersDTO param)
        {
            return base.Channel.GetLastBuyByDateAsync(param);
        }
        
        public System.Threading.Tasks.Task<wsFava.GetSaipaLotteryWinnersViewModel> GetSaipaLotteryWinnersAsync(wsFava.GetSaipaLotteryWinnersDTO param)
        {
            return base.Channel.GetSaipaLotteryWinnersAsync(param);
        }
        
        public System.Threading.Tasks.Task<wsFava.SaipaResponsePostMethodViewModel> SaipaRegisterRecivedCustomersAsync(wsFava.SaipaRegisterRecivedCustomersDTO param)
        {
            return base.Channel.SaipaRegisterRecivedCustomersAsync(param);
        }
        
        public System.Threading.Tasks.Task<wsFava.SaipaResponsePostMethodViewModel> SaipaRegisterReceivedWinnersAsync(wsFava.SaipaRegisterReceivedWinnersDTO param)
        {
            return base.Channel.SaipaRegisterReceivedWinnersAsync(param);
        }
        
        public System.Threading.Tasks.Task<string> sha3_512_hasherAsync(string input, System.Nullable<bool> useHodaPassword)
        {
            return base.Channel.sha3_512_hasherAsync(input, useHodaPassword);
        }
        
        public System.Threading.Tasks.Task<string> HodaAuthAsync()
        {
            return base.Channel.HodaAuthAsync();
        }
        
        public System.Threading.Tasks.Task<string> GetDataFromHodaAsync(string AuthAssertion, string RefId, string SpReqId)
        {
            return base.Channel.GetDataFromHodaAsync(AuthAssertion, RefId, SpReqId);
        }
        
        public System.Threading.Tasks.Task<string> VersionAsync()
        {
            return base.Channel.VersionAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IGatewayService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IGatewayService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IGatewayService))
            {
                return new System.ServiceModel.EndpointAddress("http://wsiesalefavatest.ikco.com/GatewayService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IGatewayService))
            {
                return new System.ServiceModel.EndpointAddress("https://wsiesalefavatest.ikco.ir/GatewayService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IGatewayService,
            
            BasicHttpsBinding_IGatewayService,
        }
    }
}
