//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSBSabteAhval
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://est", ConfigurationName="GSBSabteAhval.MIMTGetPersonInfoOnlineCarPortType")]
    internal interface MIMTGetPersonInfoOnlineCarPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="getEstelam3", ReplyAction="http://est/EstelamPort/getEstelam3Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EstelamResult))]
        System.Threading.Tasks.Task<GSBSabteAhval.getEstelam3Response> getEstelam3Async(GSBSabteAhval.getEstelam3Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://est")]
    public partial class PersonInfo
    {
        
        private int birthDateField;
        
        private int bookNoField;
        
        private int bookRowField;
        
        private int dateHasPostfixField;
        
        private byte[] familyField;
        
        private int familyHasPerfixField;
        
        private int familyHasPostfixField;
        
        private byte[] fatherNameField;
        
        private int genderField;
        
        private byte[] nameField;
        
        private int nameHasPerfixField;
        
        private int nameHasPostfixField;
        
        private long ninField;
        
        private int officeCodeField;
        
        private byte[] officeNameField;
        
        private int shenasnameNoField;
        
        private byte[] shenasnameSeriField;
        
        private int shenasnameSerialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int birthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int bookNo
        {
            get
            {
                return this.bookNoField;
            }
            set
            {
                this.bookNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int bookRow
        {
            get
            {
                return this.bookRowField;
            }
            set
            {
                this.bookRowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int dateHasPostfix
        {
            get
            {
                return this.dateHasPostfixField;
            }
            set
            {
                this.dateHasPostfixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=4)]
        public byte[] family
        {
            get
            {
                return this.familyField;
            }
            set
            {
                this.familyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int familyHasPerfix
        {
            get
            {
                return this.familyHasPerfixField;
            }
            set
            {
                this.familyHasPerfixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int familyHasPostfix
        {
            get
            {
                return this.familyHasPostfixField;
            }
            set
            {
                this.familyHasPostfixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=7)]
        public byte[] fatherName
        {
            get
            {
                return this.fatherNameField;
            }
            set
            {
                this.fatherNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=9)]
        public byte[] name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int nameHasPerfix
        {
            get
            {
                return this.nameHasPerfixField;
            }
            set
            {
                this.nameHasPerfixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int nameHasPostfix
        {
            get
            {
                return this.nameHasPostfixField;
            }
            set
            {
                this.nameHasPostfixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public long nin
        {
            get
            {
                return this.ninField;
            }
            set
            {
                this.ninField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public int officeCode
        {
            get
            {
                return this.officeCodeField;
            }
            set
            {
                this.officeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=14)]
        public byte[] officeName
        {
            get
            {
                return this.officeNameField;
            }
            set
            {
                this.officeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public int shenasnameNo
        {
            get
            {
                return this.shenasnameNoField;
            }
            set
            {
                this.shenasnameNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=16)]
        public byte[] shenasnameSeri
        {
            get
            {
                return this.shenasnameSeriField;
            }
            set
            {
                this.shenasnameSeriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public int shenasnameSerial
        {
            get
            {
                return this.shenasnameSerialField;
            }
            set
            {
                this.shenasnameSerialField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EstelamResult3))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(estelamResult4))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://est")]
    public partial class EstelamResult
    {
        
        private int birthDateField;
        
        private int bookNoField;
        
        private int bookRowField;
        
        private int deathStatusField;
        
        private byte[] familyField;
        
        private byte[] fatherNameField;
        
        private int genderField;
        
        private string[] messageField;
        
        private byte[] nameField;
        
        private long ninField;
        
        private int officeCodeField;
        
        private byte[] officeNameField;
        
        private int shenasnameNoField;
        
        private byte[] shenasnameSeriField;
        
        private int shenasnameSerialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int birthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int bookNo
        {
            get
            {
                return this.bookNoField;
            }
            set
            {
                this.bookNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int bookRow
        {
            get
            {
                return this.bookRowField;
            }
            set
            {
                this.bookRowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int deathStatus
        {
            get
            {
                return this.deathStatusField;
            }
            set
            {
                this.deathStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=4)]
        public byte[] family
        {
            get
            {
                return this.familyField;
            }
            set
            {
                this.familyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=5)]
        public byte[] fatherName
        {
            get
            {
                return this.fatherNameField;
            }
            set
            {
                this.fatherNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string[] message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=8)]
        public byte[] name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public long nin
        {
            get
            {
                return this.ninField;
            }
            set
            {
                this.ninField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int officeCode
        {
            get
            {
                return this.officeCodeField;
            }
            set
            {
                this.officeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=11)]
        public byte[] officeName
        {
            get
            {
                return this.officeNameField;
            }
            set
            {
                this.officeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int shenasnameNo
        {
            get
            {
                return this.shenasnameNoField;
            }
            set
            {
                this.shenasnameNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=13)]
        public byte[] shenasnameSeri
        {
            get
            {
                return this.shenasnameSeriField;
            }
            set
            {
                this.shenasnameSeriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public int shenasnameSerial
        {
            get
            {
                return this.shenasnameSerialField;
            }
            set
            {
                this.shenasnameSerialField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(estelamResult4))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://est")]
    public partial class EstelamResult3 : EstelamResult
    {
        
        private string deathDateField;
        
        private string exceptionMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string deathDate
        {
            get
            {
                return this.deathDateField;
            }
            set
            {
                this.deathDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string exceptionMessage
        {
            get
            {
                return this.exceptionMessageField;
            }
            set
            {
                this.exceptionMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://est")]
    public partial class estelamResult4 : EstelamResult3
    {
        
        private string zipcodeField;
        
        private string zipcode_DescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string zipcode
        {
            get
            {
                return this.zipcodeField;
            }
            set
            {
                this.zipcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string zipcode_Desc
        {
            get
            {
                return this.zipcode_DescField;
            }
            set
            {
                this.zipcode_DescField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEstelam3", WrapperNamespace="http://est", IsWrapped=true)]
    internal partial class getEstelam3Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://est", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://est", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://est", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://est", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://est", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GSBSabteAhval.PersonInfo arg4;
        
        public getEstelam3Request()
        {
        }
        
        public getEstelam3Request(string arg0, string arg1, string arg2, string arg3, GSBSabteAhval.PersonInfo arg4)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEstelam3Response", WrapperNamespace="http://est", IsWrapped=true)]
    internal partial class getEstelam3Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://est", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public GSBSabteAhval.EstelamResult3[] @return;
        
        public getEstelam3Response()
        {
        }
        
        public getEstelam3Response(GSBSabteAhval.EstelamResult3[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    internal interface MIMTGetPersonInfoOnlineCarPortTypeChannel : GSBSabteAhval.MIMTGetPersonInfoOnlineCarPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    internal partial class MIMTGetPersonInfoOnlineCarPortTypeClient : System.ServiceModel.ClientBase<GSBSabteAhval.MIMTGetPersonInfoOnlineCarPortType>, GSBSabteAhval.MIMTGetPersonInfoOnlineCarPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MIMTGetPersonInfoOnlineCarPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(MIMTGetPersonInfoOnlineCarPortTypeClient.GetBindingForEndpoint(endpointConfiguration), MIMTGetPersonInfoOnlineCarPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MIMTGetPersonInfoOnlineCarPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MIMTGetPersonInfoOnlineCarPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MIMTGetPersonInfoOnlineCarPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MIMTGetPersonInfoOnlineCarPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MIMTGetPersonInfoOnlineCarPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GSBSabteAhval.getEstelam3Response> GSBSabteAhval.MIMTGetPersonInfoOnlineCarPortType.getEstelam3Async(GSBSabteAhval.getEstelam3Request request)
        {
            return base.Channel.getEstelam3Async(request);
        }
        
        public System.Threading.Tasks.Task<GSBSabteAhval.getEstelam3Response> getEstelam3Async(string arg0, string arg1, string arg2, string arg3, GSBSabteAhval.PersonInfo arg4)
        {
            GSBSabteAhval.getEstelam3Request inValue = new GSBSabteAhval.getEstelam3Request();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            return ((GSBSabteAhval.MIMTGetPersonInfoOnlineCarPortType)(this)).getEstelam3Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MIMTGetPersonInfoOnlineCarHttpsSoap11Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MIMTGetPersonInfoOnlineCarHttpSoap11Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MIMTGetPersonInfoOnlineCarHttpSoap12Endpoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MIMTGetPersonInfoOnlineCarHttpsSoap12Endpoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MIMTGetPersonInfoOnlineCarHttpsSoap11Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://sr-cix.ntsw.ir/services/MIMTGetPersonInfoOnlineCar.MIMTGetPersonInfoOnlin" +
                        "eCarHttpsSoap11Endpoint");
            }
            if ((endpointConfiguration == EndpointConfiguration.MIMTGetPersonInfoOnlineCarHttpSoap11Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://sr-cix.ntsw.ir/services/MIMTGetPersonInfoOnlineCar.MIMTGetPersonInfoOnline" +
                        "CarHttpSoap11Endpoint");
            }
            if ((endpointConfiguration == EndpointConfiguration.MIMTGetPersonInfoOnlineCarHttpSoap12Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://sr-cix.ntsw.ir/services/MIMTGetPersonInfoOnlineCar.MIMTGetPersonInfoOnline" +
                        "CarHttpSoap12Endpoint");
            }
            if ((endpointConfiguration == EndpointConfiguration.MIMTGetPersonInfoOnlineCarHttpsSoap12Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://sr-cix.ntsw.ir/services/MIMTGetPersonInfoOnlineCar.MIMTGetPersonInfoOnlin" +
                        "eCarHttpsSoap12Endpoint");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            MIMTGetPersonInfoOnlineCarHttpsSoap11Endpoint,
            
            MIMTGetPersonInfoOnlineCarHttpSoap11Endpoint,
            
            MIMTGetPersonInfoOnlineCarHttpSoap12Endpoint,
            
            MIMTGetPersonInfoOnlineCarHttpsSoap12Endpoint,
        }
    }
}
